# Generated by Django 3.2.12 on 2022-02-21 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('passengers', models.PositiveIntegerField()),
                ('fuel_tank_capacity_multiplier', models.PositiveIntegerField(default=200)),
                ('fuel_consumption_multiplier', models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('passenger_fuel_increase', models.FloatField(default=0.002, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
