# Generated by Django 3.2.12 on 2022-02-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='airplane_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airplane',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
